trigger:
  batch: true
  tags:
    include:
    - '*'

stages:
  - stage: Publish
    condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/cappuccino_')
    dependsOn: []
    jobs:
      - job: Build
        pool:
          vmImage: ubuntu-latest
        timeoutInMinutes: 10
        variables:
          - name: version
            value: $[ replace(variables['Build.SourceBranch'], 'refs/tags/', '') ] 
        steps:
        - script: npm install
          displayName: 'Restore Node.js modules'
        - script: dotnet tool restore
          displayName: 'Restore .NET tools'
        - script: npm install -g vsce
          displayName: 'Install VSCode builder'
        - script: dotnet cake --target=vsix --release-version=$(version)
          displayName: 'Build VSIX'
        - task: GitHubRelease@1
          inputs:
            gitHubConnection: 'upstream'
            repositoryName: '$(Build.Repository.Name)'
            action: 'create'
            tagSource: 'gitTag'
            assets: 'artifacts/*.vsix'
