trigger:
  batch: true
  tags:
    include:
    - '*'
  branches:
    include:
    - 'main'

pool:
  vmImage: ubuntu-latest

steps:
- script: npm install
  displayName: 'Restore Node.js modules'
- script: dotnet tool restore
  displayName: 'Restore .NET tools'
- script: dotnet cake --target=vsix
  displayName: 'Build VSIX'
- publish: 'artifacts'
  displayName: 'Publish'
  artifact: Package
