trigger:
  batch: true
  tags:
    include:
    - '*'

pool:
  vmImage: ubuntu-latest

variables:
- name : version
  value: $[ replace(variables['Build.SourceBranch'], 'refs/tags/', '') ] 
# - group: Tokens

steps:
- script: npm install
  displayName: 'Restore Node.js modules'
- script: dotnet tool restore
  displayName: 'Restore .NET tools'
- script: npm install -g vsce
  displayName: 'Install VSCode builder'
- script: dotnet cake --target=vsix --release-version=$(version)
  displayName: 'Build VSIX'
- publish: 'artifacts'
  displayName: 'Publish artifacts'
  artifact: Package
- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'upstream'
    repositoryName: '$(Build.Repository.Name)'
    action: 'create'
    tagSource: 'gitTag'
    assets: 'artifacts/*.vsix'
    changeLogType: 'issueBased'
    changeLogLabels: '[{ "label" : "bug", "state" : "closed" }]'
